# Generated by Django 2.0.1 on 2018-01-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180118_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
